name: Automatisation des tests
on: push
jobs:
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compilation
        run: |
          mkdir build
          cd build
          cmake ..
          make
          make test
